# -*- coding: utf-8 -*-
"""diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S8xRRqwxnTPaLf2d5Bqwy0ANrDkGHthO
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

"""Data collection and analysis

PIMA Diabetes dataset
"""

data=pd.read_csv('/content/diabetes.csv')

data.head()

data.info()

data.shape

data.describe()

data['Outcome'].value_counts()

data.groupby('Outcome').mean()

X=data.drop(columns='Outcome',axis=1)
Y=data['Outcome']

print(X)

print(Y)

"""# **Standardize the data**"""

scaler=StandardScaler()

scaler.fit(X)

standardized_data=scaler.transform(X)

"""we can use another function called fit_transform to do functions of fit and transform in one step"""

print(standardized_data)

X=standardized_data

"""splitting to test and train data"""

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

"""Training the model"""

classifier=svm.SVC(kernel='linear')

classifier.fit(X_train,Y_train)

"""**model evaluation**"""

pred_train=classifier.predict(X_train)
train_acc=accuracy_score(pred_train,Y_train)

pred_test=classifier.predict(X_test)
test_acc=accuracy_score(pred_test,Y_test)

print('training accuracy : ',train_acc,'Test accuracy : ',test_acc)

"""making a predictive system"""

inputd=(6,148,72,35,0,33.6,0.627,50)
data_nparray=np.asarray(inputd)
data_reshaped=data_nparray.reshape(1,-1)
#standardize data
std_data=scaler.transform(data_reshaped)
prediction=classifier.predict(std_data)
if prediction==1:
  print('you have diabetes!!!')
else:
  print('you have no diabetes')

inputd=(3,126,88,41,235,39.3,0.704,27)
data_nparray=np.asarray(inputd)
data_reshaped=data_nparray.reshape(1,-1)
#standardize the data
std_data=scaler.transform(data_reshaped)
prediction=classifier.predict(std_data)
if prediction==1:
  print('you have diabetes!!!')
else:
  print('you have no diabetes')

